### ISSUE TITLE
Should depend on rubyzip >= 0.9.5

### ISSUE THREAD

**Issue by alevy** [cloudfoundry-attic/cfoundry#21]
Versions prior to 0.9.5 depend on iconv regardless of the version of Ruby used, even though Ruby version 2.0.0 does not include it in the standard library. The result is that the cfoundry gem is currently broken if rubyzip <= 0.9.4 is already installed on a system running ruby 2.

**Comment by kmayer** [comment]
+1
selenium-webdriver requires rubyzip 1.x, and older versions break with the most current Firefox (26.0) release. We've had to lock down our Gemfile and force Firefox not to update in order to run our test suite.

**Comment by cadamsdotcom** [comment]
Hi guys,

There hasn't been any activity on this issue in a while. Is this still a problem or can we close?

Regards,
CF Community Pair (@drich10 and @thecadams)

**Comment by kmayer** [comment]
Since the gem is End of Life, and everyone should be using the go cli, then
you can probably close this.

**Comment by cadamsdotcom** [comment]
No prob.

**Comment by CardboardMechanic** [comment]
It hasn't been EOL'd yet. Many teams will get around this problem by switching to CFv6, but for those still depending on the gem directly, this problem is still front and center, including the runtime and front end teams. Reopening.

**Comment by jfoley** [comment]
@alevy @TildeWill Since there is currently no owner for  this repo (and it is not actively maintained), your best bet to get this fixed is to open a PR against this. In the meantime, we are closing this issue.

Thanks,
CF Community Pair (@jfoley & @jtuchscherer)
