### ISSUE TITLE
App#upload raise => uninitialized constant CFoundry::V2::Base::JSON (NameError)

### ISSUE THREAD

**Issue by gramos** [cloudfoundry-attic/cfoundry#25]
I have an script that use cfoundry to upload an app using App#upload method
it works ok when I use cfoundry 4.3.6, but when I update to 4.7.0 it raise the error below:

/var/lib/gems/1.9.1/gems/cfoundry-4.7.0/lib/cfoundry/v2/base.rb:36:in `upload_app': uninitialized constant CFoundry::V2::Base::JSON (NameError)
        from /var/lib/gems/1.9.1/gems/cfoundry-4.7.0/lib/cfoundry/upload_helpers.rb:48:in`upload'
        from ./push_app:45:in `generate_app'

ruby -v
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]

Cheers

**Comment by CardboardMechanic** [comment]
I would have expected the `require "multi_json"` on line 1 of base.rb to take care of that. Can you run `bundle list` and paste the output here? 

Also note that you must have your own JSON library included in your project. The use of multi_json permits the library user to pick which JSON parser you want to use.

**Comment by CardboardMechanic** [comment]
Closing this issue since I believe the solution lies outside of cfoundry. Please re-open if needed.
