### ISSUE TITLE
Authorization failed (CFoundry::Denied) Error

### ISSUE THREAD

**Issue by ChampionL** [cloudfoundry-attic/cfoundry#29]
Hey, cfounry guys
#  i want to use cfoundry,when i write the sample code for my program,it occur a error, the error description follows: it told me Authorization failed, that's strange,it login successly when i use cf cli,so what's the probem? 

/home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/uaaclient.rb:151:in `rescue in authenticate_with_implicit_grant': 500: Authorization failed (CFoundry::Denied)
    from /home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/uaaclient.rb:147:in`authenticate_with_implicit_grant'
    from /home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/uaaclient.rb:25:in `block in authorize'
    from /home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/uaaclient.rb:156:in`wrap_uaa_errors'
    from /home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/uaaclient.rb:23:in `authorize'
    from /home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/concerns/login_helpers.rb:10:in`login'
#     from /home/laicb/.rvm/gems/ruby-1.9.3-p545/gems/cfoundry-4.7.2.rc1/lib/cfoundry/v2/client.rb:50:in `login'

require 'cfoundry'
endpoint = 'http://api.cloudfoundry.local"
username = 'admin'
password = 'c1oudc0w'

client = CFoundry::V2::Client.new endpoint

puts client.info

client.login(:email=>username,:password=>password)

**Comment by dieucao** [comment]
@ChampionL We no longer officially support cfoundry.
We plan to move cfoundry to cloudfoundry-community [1].  
We recommend that you use go-cli. [2]

[1] https://github.com/cloudfoundry-community
[2] https://github.com/cloudfoundry/cli
