### ISSUE TITLE
Support following redirects in BaseClient.stream_url

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-attic/cfoundry#3]
In our CF deployment we force everything through ssl.  When pushing an application we don't get staging logs because the dea provides an http based url. (https://github.com/cloudfoundry/dea_ng/issues/33).  Our load balancer redirects to https but the stage logs still fail to appear because BaseClient.stream_url doesn't follow redirects.

It would be great if BaseClient.stream_url supported following redirects similar to how RestClient does.

**Comment by jfoley** [comment]
@tlang - could you comment on this?

@aramprice / @jfoley

**Comment by youngm** [comment]
BTW https://github.com/cloudfoundry/dea_ng/issues/33 has been fixed so the root cause for this issue is no more.  However, following redirects for stream_url similar to normal requests would still be nice in case we run into something like this again in the future.

**Comment by youngm** [comment]
So did this get fixed?  Or just closed?
