### ISSUE TITLE
If cfoundry has a similar api as cf-java-client's getFile(String appName, int instanceIndex, String filePath, int startPosition, int endPosition) ?

### ISSUE THREAD

**Issue by blueden-chen** [cloudfoundry-attic/cfoundry#31]
ATT

**Comment by crhino** [comment]
Hi @chenwj,

We are having trouble understanding your question.

Are you asking if cfoundry and the cf-java-client use the same API endpoint? Or does cfoundry have a similar api as the cf-java-client? If not, we would appreciate more clarification.

Thanks,
@crhino and @jfmyers9, CF Runtime Team

**Comment by chenwj** [comment]
My problem is how to get a portion of a file in cloudfoundry by the api of cfoundry , I have found that client.request(...,"Range: bytes={start}-{end}")  can solve . I will close this issue.

**Comment by blueden-chen** [comment]
@crhino My problem is how to get a portion of a file in cloudfoundry by the api of cfoundry , I have found that client.request(...,"Range: bytes={start}-{end}") can solve it. I will close this issue.
