### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Rylon** [cloudfoundry-attic/cfoundry#32]
Hi there,

I'm trying to debug poor performance when using `CFoundry`to create a flat data structure containing all orgs, spaces, and apps for a given CF environment.

The CF environment I'm querying has around 125 running apps, with around 150 routes. The process of mapping all apps from all spaces in all orgs takes around 9 seconds, which is fine, however if we also try to map all the routes an app has, this is lazily loaded, so the process takes around 60 seconds. If we also try to map app stats, then the process starts to take longer than 5 minutes.

I enabled logging in `CFoundry` to see which CF endpoints were being called, but it seemed like there were a lot of duplicated requests, in fact for the CF environment I'm working with, it logged over 17,500 requests to the CF API to request the information required.

The code is available here, I'd really appreciate it if you could check we're not doing something bad?
https://github.com/SpringerPE/cf-light-api/blob/master/lib/cf_light_api/worker.rb#L15-L35

Can you recommend a better way to retrieve all this information?

Thanks for your help!

**Comment by dieucao** [comment]
@Rylon  We no longer officially support cfoundry.
We plan to move cfoundry to cloudfoundry-community [1].

We recommend that you use go-cli. [2]

[1] https://github.com/cloudfoundry-community
[2] https://github.com/cloudfoundry/cli

**Comment by Rylon** [comment]
Hi there,

I'm not sure the CLI is suitable in this case, as we're looking for a client library which can integrate into a web framework, and provide a simpler read-only HTTP interface onto CloudFoundry. Shelling out from this framework to a command line interface isn't really desirable for us.

If the Ruby `cfoundry` library is no longer supported, do you offer client libraries in other languages at all?

Thanks!

**Comment by dieucao** [comment]
There is a java client library that is being maintained [1]
I'm not aware of any other open source client libraries that are being maintained.
We have the api documented here [2]

[1] https://github.com/cloudfoundry/cf-java-client
[2] http://apidocs.cloudfoundry.org

**Comment by Rylon** [comment]
Ok, thank you :)
