### ISSUE TITLE
push: Nicer error if there is an invalid symlink within app; or ignore it

### ISSUE THREAD

**Issue by drnic** [cloudfoundry-attic/cfoundry#5]
In an app that had an invalid symlink, `cf push` gives the following error:

```
Upload failed. Try again with 'cf push'.
Errno::ENOENT: No such file or directory - /path/to/my/app/files
cat ~/.cf/crash # for more details
```

The root cause was that `/path/to/my/app/public/files` was a symlink to the path above. But the path above didn't exist.

Perhaps ignore the symlink.

**Comment by drnic** [comment]
Actually, the code looks like is should provide this feature. https://github.com/cloudfoundry/cfoundry/blob/master/lib/cfoundry/upload_helpers.rb#L81-L99

Ideas?

**Comment by drnic** [comment]
My gem env:

```
gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 1.8.25
  - RUBY VERSION: 1.9.3 (2013-06-27 patchlevel 448) [x86_64-darwin12.4.1]
  - INSTALLATION DIRECTORY: /Users/drnic/.rvm/gems/ruby-1.9.3-p448
  - RUBY EXECUTABLE: /Users/drnic/.rvm/rubies/ruby-1.9.3-p448/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/drnic/.rvm/gems/ruby-1.9.3-p448/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-12
  - GEM PATHS:
     - /Users/drnic/.rvm/gems/ruby-1.9.3-p448
     - /Users/drnic/.rvm/gems/ruby-1.9.3-p448@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
```

**Comment by jfoley** [comment]
@tlang - it looks like this is something we could accept a PR for, is there any work being done to support this?

@aramprice / @jfoley

**Comment by drnic** [comment]
Perhaps it's a weird edge case that'll never happen again. I was just opening the ticket to be helpful. If we close it, perhaps at least someone else will find this via google if they see the same issue and reopen it.

**Comment by dsabeti** [comment]
We're going to close this for now, since it seems there is already code for this.
